name: PyToExe
run-name: py-to-exe
on: [push, workflow_dispatch]
jobs:
  convert_to_exe:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Checkout the tast-repo
        uses: actions/checkout@v4
        with:
          repository: 'TheJBricks/tast'
          path: 'tast'
        
      - name: List files in the repository (pre-copy)
        run: ls ${{ github.workspace }}

      - name: copy files
        run: cp tast/package package
        
      - name: List files in the repository (post-copy)
        run: ls ${{ github.workspace }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --console --onefile app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app.exe
          path: dist/*
